# Generated by Django 4.2.2 on 2025-08-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unite', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisation_unite_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_organisations', to='organisation_unite.organisationunite')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations_unites', to='structure.structure')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='unite.unite')),
            ],
        ),
    ]
