# Generated by Django 4.2.2 on 2025-08-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('activated_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField()),
            ],
        ),
    ]
