# Generated by Django 4.2.2 on 2025-08-25 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherent', '0001_initial'),
        ('tuteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviTuteurAdherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('autre', 'Autre')], max_length=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='adherent.adherent')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='tuteur.tuteur')),
            ],
            options={
                'verbose_name': 'Suivi Tuteur-Adhérent',
                'verbose_name_plural': 'Suivis Tuteur-Adhérent',
                'unique_together': {('adherent', 'tuteur')},
            },
        ),
    ]
