# Generated by Django 4.2.2 on 2025-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé')], max_length=10)),
                ('numero_note', models.PositiveIntegerField(unique=True)),
                ('numero_fiche', models.PositiveIntegerField(unique=True)),
                ('type_operation', models.CharField(choices=[('recrutement', 'Recrutement'), ('mutation', 'Mutation')], max_length=12)),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
