# Generated by Django 4.2.2 on 2025-09-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0001_initial'),
        ('organisation_unite', '0001_initial'),
        ('fonction', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_employe', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='operation',
            name='id_employe_enregistre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_enregistreur', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='operation',
            name='id_employe_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_responsable', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='operation',
            name='id_fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonction.fonction'),
        ),
        migrations.AddField(
            model_name='operation',
            name='id_organisation_unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_unite.organisationunite'),
        ),
    ]
