# Generated by Django 4.2.2 on 2025-08-29 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnChargeAdherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom_complet_medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction_medecin', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite_medecin', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Prise en charge Adhérent',
                'verbose_name_plural': 'Prises en charge Adhérents',
                'ordering': ['-date_creation'],
            },
        ),
    ]
