# Generated by Django 4.2.2 on 2025-09-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prise_en_charge_adherent', '0001_initial'),
        ('adherent', '0001_initial'),
        ('operation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseenchargeadherent',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='adherent.adherent'),
        ),
        migrations.AddField(
            model_name='priseenchargeadherent',
            name='operation_enregistrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge_enregistrees', to='operation.operation'),
        ),
        migrations.AddField(
            model_name='priseenchargeadherent',
            name='operation_medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prises_en_charge_medecins', to='operation.operation'),
        ),
    ]
