# Generated by Django 4.2.2 on 2025-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_absence', models.CharField(choices=[('conge_annuel', 'Congé Annuel'), ('absence_imprevue', 'Absence Imprévue')], max_length=20)),
                ('statut', models.CharField(choices=[('annule', 'Annulé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], max_length=10)),
                ('date_debut', models.DateTimeField()),
                ('duree', models.IntegerField(help_text="Durée de l'absence en jours")),
                ('date_retour', models.DateTimeField(editable=False)),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=50)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_note', models.IntegerField(blank=True, null=True)),
                ('numero_fiche', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
    ]
