# Generated by Django 4.2.2 on 2025-08-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='id_absence_operation_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_employe', to='operation.operation'),
        ),
        migrations.AddField(
            model_name='absence',
            name='id_absence_operation_employe_enregistre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_enregistreur', to='operation.operation'),
        ),
        migrations.AddField(
            model_name='absence',
            name='id_absence_operation_employe_respensable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_responsable', to='operation.operation'),
        ),
    ]
