# Generated by Django 4.2.2 on 2025-09-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=150, unique=True)),
                ('date_creation', models.DateTimeField()),
                ('structure_sous_tutelle', models.CharField(blank=True, max_length=512, null=True)),
                ('adresse', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('lieu_residence', models.CharField(max_length=50)),
                ('pays_residence', models.CharField(max_length=50)),
                ('devise_pays', models.CharField(blank=True, max_length=30, null=True)),
                ('direction_tutelle', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_structure', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('drapeau_pays', models.ImageField(blank=True, null=True, upload_to='drapeaux/')),
                ('numero_enregistrement', models.CharField(blank=True, max_length=50, null=True)),
                ('forme_juridique', models.CharField(blank=True, max_length=50, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('contact_personne', models.CharField(blank=True, max_length=100, null=True)),
                ('domaines_activite', models.TextField(blank=True, null=True)),
                ('zones_intervention', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='Actif', max_length=20)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
