# Generated by Django 4.2.2 on 2025-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=150, unique=True)),
                ('date_creation', models.DateTimeField()),
                ('structure_sous_tutelle', models.CharField(max_length=512)),
                ('adresse', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('pays_residence', models.CharField(max_length=20)),
                ('devise_pays', models.CharField(max_length=30)),
                ('direction_tutelle', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('matricule', models.CharField(max_length=15, unique=True)),
                ('logo_structure', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('drapeau_pays', models.ImageField(blank=True, null=True, upload_to='drapeaux/')),
                ('lieu_residence', models.CharField(max_length=20)),
            ],
        ),
    ]
