# Generated by Django 4.2.2 on 2025-09-08 17:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuteur', '0001_initial'),
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mere', models.ForeignKey(blank=True, limit_choices_to={'sexe': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_mere', to='tuteur.tuteur')),
                ('pere', models.ForeignKey(blank=True, limit_choices_to={'sexe': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_pere', to='tuteur.tuteur')),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
            },
            bases=('personne.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
