# Generated by Django 4.2.2 on 2025-08-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('invalide', 'Invalide')], default='invalide', max_length=10)),
                ('type_cotisation', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], max_length=20)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_cotisation'],
            },
        ),
    ]
