# Generated by Django 4.2.2 on 2025-08-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cotisation_adherent', '0001_initial'),
        ('operation', '0002_initial'),
        ('adherent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='adherent.adherent'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='operation.operation'),
        ),
    ]
