# Generated by Django 4.2.2 on 2025-08-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
                ('fonction_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_fonctions', to='fonction.fonction')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='structure.structure')),
            ],
        ),
    ]
