# Generated by Django 4.2.2 on 2025-08-25 00:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tuteur',
                'verbose_name_plural': 'Tuteurs',
            },
            bases=('personne.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
